# application.properties
spring.application.name=carteirinha-digital

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/carteirinha_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:senhasql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

carteirinha.validade.dias=365
qr.code.validade.minutos=8

# Cloudinary (armazenamento de fotos)
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:demo}
cloudinary.api_key=${CLOUDINARY_API_KEY:000000000000000}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:secret}
app.base.url=${APP_BASE_URL:http://localhost:8080}

# JWT
jwt.secret=${JWT_SECRET:4f7vK9Xz8WqLmN2bVp9JkRt5YxCwMz1aPqRsTvUxYzA=}
jwt.expiration=86400000

aes.secret.key=${AES_SECRET:uH9fK5zNxY8mQpW2vD6rT4gL7sB1vN3mK9xP4vR8tZ0=}

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

logging.level.com.unilasalle.carteirinha.digital=DEBUG
logging.level.org.springframework.security=DEBUG